---
openapi: 3.1.0
info:
  title: space-demo
  version: 1.0.0
paths:
  /users:
    get:
      security:
      - bearerAuth:
        - read:users
        - public
  /api/users/list:
    get:
      responses:
        "200":
          description: all users listing
          content:
            application/json: {}
        "502":
          description: bad gateway
          content:
            application/json: {}
      tags:
      - get
  /api/users/list/{id}:
    get:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          minimum: 1
        description: The user ID
      responses:
        "200":
          description: user with searched ID
          content:
            application/json: {}
        "404":
          description: Not Found
          content:
            application/json: {}
        "502":
          description: bad gateway
          content:
            application/json: {}
      tags:
      - get
  /api/users/update/{id}:
    patch:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          minimum: 1
        description: The user ID
      - in: body
        name: user
        description: The user to update.
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
      responses:
        "200":
          description: user with ID updated
          content:
            application/json: {}
        "404":
          description: Not Found
          content:
            application/json: {}
        "502":
          description: bad gateway
          content:
            application/json: {}
      tags:
      - update
  /api/users/create:
    post:
      parameters:
      - in: body
        name: user
        description: The user to create.
        schema:
          type: object
          required:
          - id
          - name
          properties:
            id:
              type: integer
            name:
              type: string
            email:
              type: string
      responses:
        "201":
          description: user created
          content:
            application/json: {}
        "404":
          description: Not Found
          content:
            application/json: {}
        "502":
          description: bad gateway
          content:
            application/json: {}
      tags:
      - create
  /api/users/delete/{id}:
    delete:
      parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          minimum: 1
        description: The user ID
      responses:
        "204":
          description: user with ID deleted
          content:
            application/json: {}
        "404":
          description: Not Found
          content:
            application/json: {}
        "502":
          description: bad gateway
          content:
            application/json: {}
      tags:
      - delete
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
      description: "note: non-oauth scopes are not defined at the securityScheme level"
  schemas:
    User:
      type: object
      required:
      - id
      - name
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
    updateUser:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
    id:
      type: integer
      minimum: 1
